# ===========================
# SERVIDOR (Render)
# ===========================
server.port=${PORT:8080}

# ===========================
# BASE DE DATOS NEON
# ===========================
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require&prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===========================
# CORREO
# ===========================
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ===========================
# JWT
# ===========================
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:36000000}

# ===========================
# CORS
# ===========================
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

# ===========================
# OPTIMIZACIONES
# ===========================
spring.jpa.properties.javax.persistence.validation.mode=none
server.max-http-request-header-size=40KB